account/urls.py
from django.urls import path, include

from .views import registration


urlpatterns = [
    # Logining
    path('', include('django.contrib.auth.urls')),
    # Registration
    path('register/', registration, name='register'),
]

todo/urls.py
from django.urls import path
from . import views


app_name = 'todo'
urlpatterns = [
    path('', views.view_list, name='main'),
    path('add-task/', views.save_task, name='add_task'),
    path('<int:pk>/', views.remove_task, name='remove_task'),
    path('change-status/<int:pk>/',
         views.change_status, name='change_status'),
    # Operations for all tasks
    path('remove-all-tasks/',
         views.remove_all_tasks, name='remove_all_tasks'),
    path('activate-all-tasks/',
         views.activate_all_tasks, name='activate_all_tasks'),
    path('deactivate-all-tasks/',
         views.deactivate_all_tasks, name='deactivate_all_tasks'),
]

todoList/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('todo.urls', namespace='todo')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
]

account/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    
    class Status(models.TextChoices):
        DONE = 'Done'
        AWAITING = 'Awaiting'

    title = models.CharField(max_length=40)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='tasks')
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=8,
                              choices=Status.choices,
                              default=Status.AWAITING)


    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return self.title

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class CreateUserForm(UserCreationForm):
    #password = forms.CharField(label='Password',
    #                           widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username']

#    def clean_password2(self):
#        cd = self.cleaned_data
#        if cd['password'] != cd['password2']:
#            raise forms.ValidationError("Passwords aren't same")
#        return cd['password2']

todo/forms.py
from django import forms
from .models import Task


class CreateTaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ['title']
        

account/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect

from .services import registrator
from .forms import CreateUserForm


def registration(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    form = registrator(request)
    if form:
        return render(request,
                    'register.html',
                    {'form': CreateUserForm()})
    else:
        return redirect('/')

todo/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect

from .services import change_one_tasks_status, change_status_all_users_tasks, \
        get_datas_for_main_page, remove_all_users_tasks, \
        remove_one_users_task, save_new_users_task
from .services import TaskStatuses


@login_required
def view_list(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    return render(request,
                  'todo/main.html',
                  get_datas_for_main_page(request))


@login_required
@require_POST
def save_task(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    try:
        save_new_users_task(request)
    except Exception as er:
        return render(request,
                      'page_error.html',
                      {'error': er})
    else:
        return redirect('todo:main')


@login_required
def remove_task(request: HttpRequest,
                pk: int) -> HttpResponse | HttpResponseRedirect:
    try:
        remove_one_users_task(request, pk)
    except Exception as er:
        return render(request,
                      'page_error.html',
                      {'error': er})
    else:
        return redirect('todo:main')


@login_required
def change_status(request: HttpRequest,
                  pk: int) -> HttpResponse | HttpResponseRedirect:
    try:
        change_one_tasks_status(request, pk)
    except Exception as er:
        return render(request,
                      'page_error.html',
                      {'error': er})
    else:
        return redirect('todo:main')


@login_required
@require_POST
def remove_all_tasks(request: HttpRequest
                     ) -> HttpResponse | HttpResponseRedirect:
    try:
        remove_all_users_tasks(request)
    except Exception as er:
        return render(request,
                      'page_error.html',
                      {'error': er})
    else:
        return redirect('todo:main')


@login_required
@require_POST
def deactivate_all_tasks(request: HttpRequest
                         ) -> HttpResponse | HttpResponseRedirect:
    try:
        change_status_all_users_tasks(request, TaskStatuses.done)
    except Exception as er:
        return render(request,
                      'page_error.html',
                      {'error': er})
    else:
        return redirect('todo:main')


@login_required
@require_POST
def activate_all_tasks(request: HttpRequest
                       ) -> HttpResponse | HttpResponseRedirect:
    try:
        change_status_all_users_tasks(request, TaskStatuses.awaiting)
    except Exception as er:
        return render(request,
                      'page_error.html',
                      {'error': er})
    else:
        return redirect('todo:main')

templates/base.html
{% load static %}


<!DOCTYPE html>

<html>
  <head>
    <title>
      {% block title %}
      {% endblock %}
    </title>
    <link href="{% static "css/todos.css" %}" rel="stylesheet">
  </head>
  <body>
    <a href="{% url "todo:main" %}">
      <h1 class="main_title">
        ToDo
      </h1>
    </a>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

templates/includes/account.html
<h1 style="color: Orange">
  Your account
</h1>
<div class="navigation">
  <form method="post" action="{% url "logout" %}">
    {% csrf_token %}
    <p><input class="logout-bttn" type="submit" value="Log out"></p>
  </form>
  <a href="{% url "password_change" %}">
    <input class="chng-passw"
           type="button"
           value="Change password">
  </a>
</div>
<div class="navigation">
  <form method="post" action="{% url "todo:activate_all_tasks" %}">
    {% csrf_token %}
    <input class="Awaiting"
           type="submit"
           value="Activate all tasks">
  </form>
  <form method="post" action="{% url "todo:deactivate_all_tasks" %}">
    {% csrf_token %}
    <input class="Done"
           type="submit"
           value="Deactivate all tasks">
  </form>
</div>
<div class="navigation">
  <form method="post" action="{% url "todo:remove_all_tasks" %}">
    {% csrf_token %}
    <input class="del-bttn"
           type="submit"
           value="Delete all tasks">
  </form>
</div>

templates/page_error.html
{% extends "base.html" %}


{% block title %}error{% endblock %}

{% block content %}
  <div class="content">
    <h1 class="title">Error!!</h1>
    <h2 style=" color: red; ">{{ error }}</h2>
  </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}


{% block title %}registration{% endblock %}

{% block content %}
<div class="content">
  <h2 class="title" >Registration</h2>
  {% if answer %}
    <p>{{ answer }}</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="acc-bttn" type="submit" value="Register to">
  </form>
  <p>
    If you already have an account.
    Go<a href="{% url "login" %}">there</a>for log-in.
  </p>
</div>
{% endblock %}

templates/todo/main.html
{% extends "base.html" %}


{% block title %}main page{% endblock %}

{% block content %}
  {% if request.user.is_authenticated %}
    <div class="content">
      {% if task_list %}
      <h1 class="title">
        {{ user.username }}'s ToDo List:
      </h1>
      {% if messages %}
        {% for message in messages %}
          <p>{{ message|safe }}</p>
        {% endfor %}
      {% endif%}
        {% for task in task_list %}
          <div class="task">
            <p style="font-size: 18px;">{{ task.title }}</p>
            <p style="font-style: italic;
                      font-size: 12px;
                      color: gray;">{{ task.created }}</p>
            <p>
              {{ task.is_done }}
              <div class="navigation">
                <a href="{% url "todo:remove_task" task.id %}">
                  <input class="del-bttn" type="button" value="Delete task">
                </a>
                <a href="{% url "todo:change_status" task.id %}">
                  <input class="{{ task.status }}"
                         type="button"
                         value="{{ task.status }}">
                </a>
              </div>
            </p>
          </div>
        {% endfor %}
      {% else %}
        <h1 class="title">
          Hello, {{ user.username }}. Your task list is empty yet
        </h1>
      {% endif %}
      <div class="task-form">
        <p>
          Add task:
        </p>
        <form method="post" action="{% url "todo:add_task" %}">
          {% csrf_token %}
          {{ form.as_p }}
          <input class="add-bttn" type="submit" value="Add task">
        </form>
      </div>
    </div>
    <div class="sidebar">
      {% include "includes/account.html" %}
    </div>
  {% endif %}
{% endblock %}